package com.biomed.smarttrak.admin;

import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import com.biomed.smarttrak.action.AdminControllerAction;
import com.biomed.smarttrak.action.AdminControllerAction.Section;
import com.biomed.smarttrak.action.AdminControllerAction.Status;
import com.biomed.smarttrak.action.ProductAction;
import com.biomed.smarttrak.util.BiomedProductIndexer;
import com.biomed.smarttrak.util.ManagementActionUtil;
import com.biomed.smarttrak.vo.ProductAllianceVO;
import com.biomed.smarttrak.vo.ProductAttributeTypeVO;
import com.biomed.smarttrak.vo.ProductAttributeVO;
import com.biomed.smarttrak.vo.ProductVO;
import com.biomed.smarttrak.vo.RegulationVO;
import com.biomed.smarttrak.vo.SectionVO;
import com.siliconmtn.action.ActionException;
import com.siliconmtn.action.ActionRequest;
import com.siliconmtn.data.Node;
import com.siliconmtn.data.Tree;
import com.siliconmtn.db.DBUtil;
import com.siliconmtn.db.orm.DBProcessor;
import com.siliconmtn.db.util.DatabaseException;
import com.siliconmtn.exception.InvalidDataException;
import com.siliconmtn.http.parser.StringEncoder;
import com.siliconmtn.util.Convert;
import com.siliconmtn.util.EnumUtil;
import com.siliconmtn.util.StringUtil;
import com.siliconmtn.util.UUIDGenerator;
import com.smt.sitebuilder.common.PageVO;
import com.smt.sitebuilder.common.constants.Constants;
import com.smt.sitebuilder.search.SearchDocumentHandler;

/****************************************************************************
 * <b>Title</b>: ProductManagementAction.java <p/>
 * <b>Project</b>: WC_Custom <p/>
 * <b>Description: </b> Manages products for the biomed gps site.
 * <p/>
 * <b>Copyright:</b> Copyright (c) 2017<p/>
 * <b>Company:</b> Silicon Mountain Technologies<p/>
 * @author Eric Damschroder
 * @version 1.0
 * @since Feb 1, 2017<p/>
 * <b>Changes: </b>
 ****************************************************************************/
public class ProductManagementAction extends ManagementAction {

	public static final String ACTION_TARGET = "actionTarget";

	public static final String DETAILS_ID = "DETAILS_ROOT";

	public static final String CONTENT_ATTRIBUTE_ID = "CONTENT";

	private enum ActionTarget {
		PRODUCT, PRODUCTATTRIBUTE, ATTRIBUTE, PRODUCTLINK, PRODUCTATTACH,
		ATTRIBUTELIST, ALLIANCE, DETAILSATTRIBUTE, REGULATION, PREVIEW, PRODUCTATTRIBUTEARCHIVE, PRODUCTATTRIBUTEARCHIVEUPDATE
	}

	/**
	 * Enum for ensuring that the details fields are presented in the proper order
	 */
	private enum DetailsField {
		CLASSIFICATION(0, 2),
		APPROACH(1, 1),
		MARKET(2, 4),
		TECHNOLOGY(3, 3),
		INDICATION(4, 5);

		int order;
		int publicOrder;

		DetailsField(int order, int publicOrder) {
			this.order = order;
			this.publicOrder = publicOrder;
		}

		public int getOrder() {
			return order;
		}

		public int getPublicOrder() {
			return publicOrder;
		}

		public static DetailsField getFromString(String detailField) {
			if (StringUtil.isEmpty(detailField)) return null;
			try {
				return DetailsField.valueOf(detailField);
			} catch (Exception e) {
				log.error("Error getting details field: ", e);
				return null;
			}
		}
	}


	/**
	 * Enum for handling sort values passed to the action
	 * by the bootstrap table
	 */
	private enum SortField {
		PRODUCTNAME("PRODUCT_NM"),
		STATUSNO("p.STATUS_NO"),
		COMPANYNAME("COMPANY_NM"),
		ORDERNO("p.ORDER_NO");

		private String dbField;

		SortField(String dbField) {
			this.dbField = dbField;
		}

		public String getDbField() {
			return dbField;
		}

		public static SortField getFromString(String sortField) {
			if (StringUtil.isEmpty(sortField)) return SortField.PRODUCTNAME;
			try {
				return SortField.valueOf(sortField.toUpperCase());
			} catch (Exception e) {
				log.error("Error getting sort field: ", e);
				return SortField.PRODUCTNAME;
			}
		}
	}

	/**
	 * Content that can be autogenerated on
	 * creation of a new product
	 */
	private enum ContentType {
		DESCRIPTION("Product Description", 1),
		INDICATION("Indication", 5),
		UPDATE("Clinical Update", 10),
		STATUS("Regulatory Status", 15),
		SALES("Sales & Distribution", 30);

		private String contentName;
		private int order;

		private ContentType(String contentName, int order) {
			this.contentName = contentName;
			this.order = order;
		}

		public String getContentName() {
			return contentName;
		}

		public int getOrder() {
			return order;
		}

		public static ContentType getFromString(String contentType) {
			if (StringUtil.isEmpty(contentType)) return null;
			try {
				return ContentType.valueOf(contentType);
			} catch (Exception e) {
				log.error("Error getting content type: ", e);
				return null;
			}
		}
	}

	/*
	 * (non-Javadoc)
	 * @see com.smt.sitebuilder.action.SBActionAdapter#list(com.siliconmtn.action.ActionRequest)
	 */
	@Override
	public void list(ActionRequest req) throws ActionException {
		super.retrieve(req);
	}

	/*
	 * (non-Javadoc)
	 * @see com.smt.sitebuilder.action.SBActionAdapter#delete(com.siliconmtn.action.ActionRequest)
	 */
	@Override
	public void delete(ActionRequest req) throws ActionException {
		req.setParameter("buildAction","delete");
		this.build(req);
	}

	/*
	 * (non-Javadoc)
	 * @see com.smt.sitebuilder.action.SBActionAdapter#retrieve(com.siliconmtn.action.ActionRequest)
	 */
	@Override
	public void retrieve(ActionRequest req) throws ActionException {
		if (req.hasParameter("buildAction")) {
			super.retrieve(req);
			return;
		}

		ActionTarget action;
		try {
			action = ActionTarget.valueOf(req.getParameter(ACTION_TARGET));
		} catch (Exception e) {
			action = ActionTarget.PRODUCT;
		}

		switch (action) {
			case PRODUCT:
				retrieveProduct(req);
				break;
			case PRODUCTATTRIBUTEARCHIVE:
				retrieveArchives(req);
				break;
			case PRODUCTLINK:
			case PRODUCTATTACH:
			case PRODUCTATTRIBUTE:
				productAttributeRetrieve(req);
				break;
			case ATTRIBUTE:
				attributeRetrieve(req);
				break;
			case ATTRIBUTELIST:
				super.putModuleData(getProductAttributes(req.getParameter("productId"), req.getParameter("attributeTypeCd")));
				break;
			case ALLIANCE:
				allianceRetrieve(req);
				break;
			case DETAILSATTRIBUTE:
				retrieveModuleSets(req, null);
				break;
			case REGULATION:
				retrieveRegulatory(req);
				break;
			case PREVIEW:
				retrievePreview(req);
				break;
			default:
				break;
		}
	}

	/**
	 * Load Company Attribute Archive records.
	 * @param req
	 * @throws ActionException 
	 */
	private void retrieveArchives(ActionRequest req) {
		String attributeType = req.getParameter("attributeTypeCd");
		String productAttributeGroupId = req.getParameter("productAttributeGroupId");
		List<Object> params = new ArrayList<>();

		StringBuilder sql = new StringBuilder(150);
		sql.append(DBUtil.SELECT_FROM_STAR);
		sql.append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR xr ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE a ");
		sql.append("on a.ATTRIBUTE_ID = xr.ATTRIBUTE_ID ");
		sql.append(DBUtil.WHERE_1_CLAUSE);
		if (!StringUtil.isEmpty(attributeType)) {
			sql.append("and TYPE_CD = ? ");
			params.add(attributeType);
		}
		sql.append("and xr.product_attribute_group_id = ? and xr.product_attribute_id != ?");
		sql.append("ORDER BY xr.create_dt desc ");
		params.add(productAttributeGroupId);
		params.add(productAttributeGroupId);

		log.debug(sql+"|"+productAttributeGroupId+"|"+attributeType);
		DBProcessor db = new DBProcessor(dbConn);

		// DBProcessor returns a list of objects that need to be individually cast to attributes
		List<Object> results = db.executeSelect(sql.toString(), params, new ProductAttributeVO());
		putModuleData(results, results.size(), false);
	}

	/**
	 * Get the product as it would appear on the public side.
	 * @param req
	 * @throws ActionException
	 */
	protected void retrievePreview(ActionRequest req) throws ActionException {
		//set data for downstream
		setAttribute(Constants.SITE_DATA, req.getAttribute(Constants.SITE_DATA));
		setAttribute(Constants.PAGE_PREVIEW, true);
		
		ProductAction pa = new ProductAction(actionInit);
		pa.setDBConnection(dbConn);
		pa.setAttributes(attributes);
		super.putModuleData(pa.retrieveProduct(req.getParameter("productId"), AdminControllerAction.STAFF_ROLE_LEVEL));
	}


	/**
	 * Get regulations associated with a product or an id
	 */
	protected void retrieveRegulatory(ActionRequest req) {
		StringBuilder sql = new StringBuilder(475);
		sql.append(DBUtil.SELECT_FROM_STAR).append(customDbSchema).append("BIOMEDGPS_PRODUCT_REGULATORY r ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_REGULATORY_STATUS s ");
		sql.append("ON s.STATUS_ID = r.STATUS_ID ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_REGULATORY_REGION re ");
		sql.append("ON re.REGION_ID = r.REGION_ID ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_REGULATORY_PATH p ");
		sql.append("ON p.PATH_ID = r.PATH_ID ");
		sql.append("WHERE r.PRODUCT_ID = ? ");
		sql.append("and r.REGULATORY_ID = ? ");

		List<Object> params = new ArrayList<>();
		params.add(req.getParameter("productId"));
		params.add(req.getParameter("regulatoryId"));

		DBProcessor db = new DBProcessor(dbConn);
		List<Object> results = db.executeSelect(sql.toString(), params, new RegulationVO());

		if (results.isEmpty()) {
			super.putModuleData(new RegulationVO());
		} else {
			super.putModuleData(results.get(0));
		}
	}


	/**
	 * Get information neccesary to populate product attribute pages
	 * @param req
	 */
	private void productAttributeRetrieve(ActionRequest req) {
		if (req.hasParameter("productAttributeId"))
			retrieveProductAttribute(req);
	}


	/**
	 * Determine what kind of attribute data needs to be retrieved and do so.
	 * @param req
	 */
	protected void attributeRetrieve(ActionRequest req) {
		if (req.hasParameter("attributeId")) {
			retrieveAttribute(req.getParameter("attributeId"));
		} else if (!req.hasParameter("add")){
			retrieveAttributes(req);
		}
	}


	/**
	 * Get all available module sets and flag all that are assigned to a product
	 * @param req
	 * @throws ActionException
	 */
	protected void retrieveModuleSets(ActionRequest req, ProductVO p) throws ActionException {
		StringBuilder sql = new StringBuilder(550);
		sql.append("select a.attribute_id, a.parent_id, a.attribute_nm, string_agg(pm.moduleset_id, ',') as section_ids ");
		sql.append("from ").append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE a ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_PRODUCT_MODULESET_XR xr ");
		sql.append("on xr.attribute_id = a.attribute_id ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_PRODUCT_MODULESET pm ");
		sql.append("on pm.moduleset_id = xr.moduleset_id ");
		sql.append("group by a.attribute_id, a.parent_id, a.attribute_nm ");
		sql.append("order by a.attribute_nm ");
		log.debug(sql);
		List<Node> attributes = new ArrayList<>();

		List<String> activeDetails = getAssingedAttributes(req.getParameter("productId"));

		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ResultSet rs = ps.executeQuery();

			while (rs.next()) {
				ProductAttributeTypeVO attr = new ProductAttributeTypeVO();
				attr.setAttributeId(rs.getString("attribute_id"));
				attr.setAttributeName(rs.getString("attribute_nm"));
				attr.addSectionIds(rs.getString("section_ids"));
				attr.setParentId(rs.getString("parent_id"));
				if (activeDetails.contains(attr.getAttributeId()))
					attr.setActiveFlag(1);
				Node n = new Node(attr.getAttributeId(), attr.getParentId());
				n.setUserObject(attr);
				attributes.add(n);
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}

		Tree t = new Tree(attributes);
		t.setRootNode(t.findNode(DETAILS_ID));
		if (p == null) {
			super.putModuleData(orderModuleSets(t.getRootNode()));
		} else {
			p.setDetailsList(orderModuleSets(t.getRootNode()));
		}
	}


	/**
	 * Get the details nodes and put them in the proper order.
	 * @param rootNode
	 * @return
	 */
	protected Node[] orderModuleSets(Node rootNode) {
		Node[] nodes = new Node[DetailsField.values().length];

		for (Node n : rootNode.getChildren()) {
			DetailsField detail = DetailsField.getFromString(n.getNodeId());
			if(detail != null) 
				nodes[detail.getOrder()] = n;
		}

		return nodes;
	}


	/**
	 * Get a list of all assigned attributes for a product
	 * @param productId
	 * @return
	 * @throws ActionException
	 */
	protected List<String> getAssingedAttributes(String productId) throws ActionException {
		StringBuilder sql = new StringBuilder(150);
		sql.append("select ATTRIBUTE_ID from ").append(customDbSchema);
		sql.append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR where PRODUCT_ID = ? ");
		log.debug(sql+"|"+productId);
		List<String> activeDetails = new ArrayList<>();
		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, productId);

			ResultSet rs = ps.executeQuery();

			while(rs.next()) {
				activeDetails.add(rs.getString("ATTRIBUTE_ID"));
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}

		return activeDetails;
	}


	/**
	 * Determine how to retrieve product information and do so.
	 * @param req
	 * @throws ActionException
	 */
	protected void allianceRetrieve(ActionRequest req) {
		if (req.hasParameter("allianceId"))
			retrieveAlliance(req.getParameter("allianceId"));
	}


	/**
	 * Retrieve all information pertaining to a particular alliance
	 * @param allianceId
	 */
	protected void retrieveAlliance(String allianceId) {
		StringBuilder sql = new StringBuilder(100);
		sql.append(DBUtil.SELECT_FROM_STAR).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ALLIANCE_XR ");
		sql.append("WHERE PRODUCT_ALLIANCE_XR_ID = ? ");

		List<Object> params = new ArrayList<>();
		params.add(allianceId);
		DBProcessor db = new DBProcessor(dbConn);
		ProductAllianceVO alliance = (ProductAllianceVO) db.executeSelect(sql.toString(), params, new ProductAllianceVO()).get(0);
		super.putModuleData(alliance);
	}


	/**
	 * Determine whether to get one product or all and do so.
	 * @param req
	 * @throws ActionException
	 */
	protected void retrieveProduct(ActionRequest req) throws ActionException {
		if (req.hasParameter("productId") && ! req.hasParameter("add")) {
			retrieveProduct(req.getParameter("productId"), req);
		} else if (!req.hasParameter("add")) {
			retrieveProducts(req);
		} else {
			loadAuthors(req); //load list of BiomedGPS Staff for the "Author" drop-down
			//TODO Cleanup hierarchy loading/caching code - Zoho SC-230
			if (req.getSession().getAttribute("hierarchyTree") == null) {
				// This is a form for a new market make sure that the hierarchy tree is present 
				Tree t = loadDefaultTree();
				req.getSession().setAttribute("hierarchyTree", t.preorderList());
			}
		}
	}


	/**
	 * get a particular product attribute from the database for editing
	 * @param req
	 */
	protected void retrieveProductAttribute(ActionRequest req) {
		StringBuilder sql = new StringBuilder(300);
		sql.append("SELECT xr.*, a.TYPE_CD FROM ").append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR xr ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE a ");
		sql.append("ON a.ATTRIBUTE_ID = xr.ATTRIBUTE_ID ");
		sql.append("WHERE PRODUCT_ATTRIBUTE_ID = ? ");
		sql.append("ORDER BY xr.order_no");

		List<Object> params = new ArrayList<>();
		params.add(req.getParameter("productAttributeId"));
		DBProcessor db = new DBProcessor(dbConn);
		ProductAttributeVO attr = db.executeSelect(sql.toString(), params, new ProductAttributeVO()).get(0);
		super.putModuleData(attr);
		req.setParameter("rootNode", attr.getAttributeId());
	}


	/**
	 *Retrieve all attributes available to the product.
	 * @param req
	 */
	protected void retrieveAttributes(ActionRequest req) {
		StringBuilder sql = new StringBuilder(100);
		List<Object> params = new ArrayList<>();
		sql.append(DBUtil.SELECT_FROM_STAR).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE ");
		if (req.hasParameter(DBUtil.TABLE_SEARCH)) {
			sql.append("WHERE lower(ATTRIBUTE_NM) like ? ");
			params.add("%" + req.getParameter(DBUtil.TABLE_SEARCH).toLowerCase() + "%");
		}
		if (req.hasParameter("attributeTypeCd")) {
			sql.append("WHERE TYPE_CD = ? ");
			params.add(req.getParameter("attributeTypeCd"));
		}

		sql.append("ORDER BY ORDER_NO ");
		log.debug(sql);
		DBProcessor db = new DBProcessor(dbConn);
		List<Object> results = db.executeSelect(sql.toString(), params, new ProductAttributeTypeVO());
		List<Node> orderedResults = new ArrayList<>();
		for (Object o : results) {
			ProductAttributeTypeVO attr = (ProductAttributeTypeVO)o;
			Node n = new Node(attr.getAttributeId(), attr.getParentId());
			n.setUserObject(attr);
			orderedResults.add(n);
		}
		storeAttributeData(req, orderedResults);
	}


	/**
	 * Determine where and how much attribute data to save.
	 * @param req
	 * @param orderedResults
	 */
	private void storeAttributeData(ActionRequest req, List<Node> orderedResults) {
		int rpp = Convert.formatInteger(req.getParameter(DBUtil.TABLE_LIMIT), 10);
		int page = Convert.formatInteger(req.getParameter(DBUtil.TABLE_OFFSET), 0)/rpp;
		int end = orderedResults.size() < rpp*(page+1)? orderedResults.size() : rpp*(page+1);

		// If all attributes of a type is being requested set it as a request attribute since it is
		// being used to supplement the attribute xr editing.
		// Search data should not be turned into a tree after a search as requisite nodes may be missing
		if (req.hasParameter(DBUtil.TABLE_SEARCH)) {
			super.putModuleData(orderedResults.subList(rpp*page, end), orderedResults.size(), false);
		} else {
			super.putModuleData(new Tree(orderedResults).getPreorderList().subList(rpp*page, end), orderedResults.size(), false);
		}
	}


	/**
	 * Ensure that we are getting a top level root node.
	 * @param t
	 * @param rootNode
	 * @return
	 */
	protected Node getTopParent(Tree t, Node rootNode) {
		if (rootNode.getParentId() != null) {
			return getTopParent(t, t.findNode(rootNode.getParentId()));
		}
		return rootNode;
	}


	/**
	 * Get the details of the supplied attribute type
	 * @param attributeId
	 */
	protected void retrieveAttribute(String attributeId) {
		StringBuilder sql = new StringBuilder(100);
		List<Object> params = new ArrayList<>();
		sql.append(DBUtil.SELECT_FROM_STAR).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE ");
		sql.append("WHERE ATTRIBUTE_ID = ? ");
		params.add(attributeId);
		log.debug(sql);
		DBProcessor db = new DBProcessor(dbConn);
		List<Object> res = db.executeSelect(sql.toString(), params, new ProductAttributeTypeVO());

		if (!res.isEmpty()) {
			ProductAttributeTypeVO attr = db.executeSelect(sql.toString(), params, new ProductAttributeTypeVO()).get(0);
			super.putModuleData(attr);
		} else {
			super.putModuleData(new ProductAttributeTypeVO());
		}
	}


	/**
	 * Retrieve all companies from the database as well as create a flag that 
	 * shows whether the product has been invested in by another product.
	 * @param req
	 * @throws ActionException
	 */
	protected void retrieveProducts(ActionRequest req) throws ActionException {
		List<Object> params = new ArrayList<>();
		StringBuilder sql = new StringBuilder(100);
		sql.append("select * ").append("FROM ").append(customDbSchema).append("BIOMEDGPS_product p ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_COMPANY c ");
		sql.append("ON c.COMPANY_ID = p.COMPANY_ID ");
		sql.append("WHERE 1=1 ");

		// If the request has search terms on it add them here
		if (req.hasParameter(DBUtil.TABLE_SEARCH)) {
			sql.append("and (lower(PRODUCT_NM) like ? ");
			params.add("%" + req.getParameter(DBUtil.TABLE_SEARCH).toLowerCase() + "%");
			sql.append("or lower(COMPANY_NM) like ? )");
			params.add("%" + req.getParameter(DBUtil.TABLE_SEARCH).toLowerCase() + "%");
		}

		if (!req.hasParameter("inactive")) {
			sql.append("and (p.STATUS_NO = '").append(Status.P.toString()).append("' ");
			sql.append("or p.STATUS_NO = '").append(Status.E.toString()).append("') ");
		}

		if (req.hasParameter("authorId")) {
			sql.append("and p.creator_profile_id = ? ");
			params.add(req.getParameter("authorId"));
		}

		SortField s = SortField.getFromString(req.getParameter("sort"));

		sql.append("ORDER BY ").append(s.getDbField());
		sql.append(" ").append(req.hasParameter(DBUtil.TABLE_ORDER)? req.getParameter(DBUtil.TABLE_ORDER):DBUtil.SortDirection.ASC.name()).append(" ");

		int limit  = Convert.formatInteger(req.getParameter(DBUtil.TABLE_LIMIT));
		if (limit != 0) {
			sql.append("LIMIT ? OFFSET ? ");
			params.add(Convert.formatInteger(req.getParameter(DBUtil.TABLE_LIMIT)));
			params.add(Convert.formatInteger(req.getParameter(DBUtil.TABLE_OFFSET)));
		}
		log.debug(sql);

		DBProcessor db = new DBProcessor(dbConn);
		List<Object> products = db.executeSelect(sql.toString(), params, new ProductVO());
		super.putModuleData(products, getProductCount(req.getParameter(DBUtil.TABLE_SEARCH), req.getParameter("authorId"), req.hasParameter("inactive")), false);
	}


	/**
	 * Get a count of how many products are in the database
	 * @return
	 * @throws ActionException 
	 */
	protected int getProductCount(String searchData, String authorId, boolean inactive) throws ActionException {
		StringBuilder sql = new StringBuilder(150);
		sql.append("select COUNT(*) ").append("FROM ").append(customDbSchema).append("BIOMEDGPS_product p ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_COMPANY c ");
		sql.append("ON p.COMPANY_ID = c.COMPANY_ID ");
		sql.append("WHERE 1=1 ");
		// If the request has search terms on it add them here
		if (!StringUtil.isEmpty(searchData)) {
			sql.append("and (lower(PRODUCT_NM) like ? ");
			sql.append("or lower(COMPANY_NM) like ? )");
		}

		if (!inactive) {
			sql.append("and (p.STATUS_NO = '").append(Status.P.toString()).append("' ");
			sql.append("or p.STATUS_NO = '").append(Status.E.toString()).append("') ");
		}

		if (!StringUtil.isEmpty(authorId)) {
			sql.append("and p.creator_profile_id = ? ");
		}

		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			int i = 1;			
			if (!StringUtil.isEmpty(searchData)) {
				ps.setString(i++, "%" + searchData.toLowerCase() + "%");
				ps.setString(i++, "%" + searchData.toLowerCase() + "%");
			}
			if (!StringUtil.isEmpty(authorId)) ps.setString(i, authorId);
			ResultSet rs = ps.executeQuery();
			if (rs.next())
				return rs.getInt(1);
		} catch (SQLException e) {
			throw new ActionException(e);
		}

		return 0;
	}


	/**
	 * Get all information related to the supplied product.
	 * @param productId
	 * @throws ActionException
	 */
	protected void retrieveProduct(String productId, ActionRequest req) throws ActionException {
		ProductVO product;
		StringBuilder sql = new StringBuilder(100);
		sql.append(DBUtil.SELECT_FROM_STAR).append(customDbSchema).append("BIOMEDGPS_PRODUCT ");
		sql.append("WHERE PRODUCT_ID = ? ");

		List<Object> params = new ArrayList<>();
		params.add(productId);
		DBProcessor db = new DBProcessor(dbConn);
		product = (ProductVO) db.executeSelect(sql.toString(), params, new ProductVO()).get(0);

		Tree t = loadDefaultTree();
		req.getSession().setAttribute("hierarchyTree", t.preorderList());
		req.getSession().setAttribute("productName", product.getProductName());
		req.getSession().setAttribute("shortProductName", product.getShortName());
		req.getSession().setAttribute("productNameParam", StringEncoder.urlEncode(product.getProductName()));

		String jsonType = req.getParameter("jsonType");
		if ("alliance".equals(jsonType)) {
			addAlliances(product);
		}  else if ("attribute".equals(jsonType)) {
			addAttributes(product, req.getParameter("attributeTypeCd"));
		} else if ("regulation".equals(jsonType)) {
			addRegulations(product);
		} else {
			// This is a main product retrieve. Therefore we need product details as well
			retrieveModuleSets(req, product);
		}


		getActiveSections(product);
		loadAuthors(req); //load list of BiomedGPS Staff for the "Author" drop-down
		super.putModuleData(product);
	}


	/**
	 * Get all regulations associated to this product and add them
	 * @param product
	 */
	protected void addRegulations(ProductVO product) {
		StringBuilder sql = new StringBuilder(475);
		sql.append(DBUtil.SELECT_FROM_STAR).append(customDbSchema).append("BIOMEDGPS_PRODUCT_REGULATORY r ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_REGULATORY_STATUS s ");
		sql.append("ON s.STATUS_ID = r.STATUS_ID ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_REGULATORY_REGION re ");
		sql.append("ON re.REGION_ID = r.REGION_ID ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_REGULATORY_PATH p ");
		sql.append("ON p.PATH_ID = r.PATH_ID ");
		sql.append("WHERE r.PRODUCT_ID = ? ");
		log.debug(sql);

		List<Object> params = new ArrayList<>();
		params.add(product.getProductId());

		DBProcessor db = new DBProcessor(dbConn);
		List<Object> results = db.executeSelect(sql.toString(), params, new RegulationVO());
		for (Object o : results) 
			product.addRegulation((RegulationVO)o);
	}


	/**
	 * Get all alliances the supplied product is in and add them to the vo
	 * @param product
	 */
	protected void addAlliances(ProductVO product) {
		StringBuilder sql = new StringBuilder(525);
		sql.append(DBUtil.SELECT_FROM_STAR).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ALLIANCE_XR pax ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_ALLIANCE_TYPE at ");
		sql.append("ON pax.ALLIANCE_TYPE_ID = at.ALLIANCE_TYPE_ID ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_PRODUCT p  ");
		sql.append("ON p.PRODUCT_ID = pax.PRODUCT_ID ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_COMPANY c ");
		sql.append("ON c.COMPANY_ID = pax.COMPANY_ID ");
		sql.append("WHERE pax.PRODUCT_ID = ? ");
		sql.append("ORDER BY pax.ORDER_NO ");

		List<Object> params = new ArrayList<>();
		params.add(product.getProductId());
		DBProcessor db = new DBProcessor(dbConn);

		// DBProcessor returns a list of objects that need to be individually cast to alliances
		List<Object> results = db.executeSelect(sql.toString(), params, new ProductAllianceVO());
		for (Object o : results) {
			product.addAlliance((ProductAllianceVO)o);
		}
	}


	/**
	 * Get all the sections that are associated with the supplied product
	 * @param product
	 * @throws ActionException
	 */
	protected void addSections(ProductVO product) throws ActionException {
		StringBuilder sql = new StringBuilder(275);
		sql.append("SELECT SECTION_NM, xr.PRODUCT_SECTION_XR_ID, xr.SECTION_ID FROM ").append(customDbSchema).append("BIOMEDGPS_PRODUCT_SECTION xr ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_SECTION s ");
		sql.append("ON s.SECTION_ID = xr.SECTION_ID ");
		sql.append("WHERE PRODUCT_ID = ? ");

		Tree t = loadDefaultTree();
		t.buildNodePaths();
		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, product.getProductId());

			ResultSet rs = ps.executeQuery();

			while(rs.next()) {
				SectionVO sec = new SectionVO(rs);
				sec.setSectionId(rs.getString("PRODUCT_SECTION_XR_ID"));
				sec.setSectionNm(rs.getString("SECTION_NM"));
				setGroupName(t.findNode(rs.getString("SECTION_ID")), sec);
				product.addProductSection(sec);
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Set the group name based on the full path of the supplied node.
	 * @param n
	 * @param sec
	 */
	private void setGroupName(Node n, SectionVO sec) {
		if (n == null) return;
		String[] parts = n.getFullPath().split(SearchDocumentHandler.HIERARCHY_DELIMITER);
		if (parts.length < 2) {
			sec.setGroupNm(parts[0]);
		} else {
			sec.setGroupNm(parts[1]);
		}
	}


	/**
	 * Gets all sections that have been assigned to the supplied product
	 * @param productId
	 * @return
	 * @throws ActionException
	 */
	protected List<String> getActiveSections(ProductVO product) throws ActionException {
		StringBuilder sql = new StringBuilder(150);
		sql.append("SELECT SECTION_ID FROM ").append(customDbSchema);
		sql.append("BIOMEDGPS_PRODUCT_SECTION WHERE PRODUCT_ID = ? ");

		List<String> activeSections = new ArrayList<>();
		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, product.getProductId());

			ResultSet rs = ps.executeQuery();

			while (rs.next()) {
				product.addProductSection(new SectionVO(rs));
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}

		return activeSections;

	}


	/**
	 * Get all attributes associated with the supplied product.
	 * @param product
	 * @throws ActionException 
	 */
	protected void addAttributes(ProductVO product, String attributeType) {
		List<Object> results = getProductAttributes(product.getProductId(), attributeType);

		for (Object o : results) {
			ProductAttributeVO p = (ProductAttributeVO)o;
			product.addProductAttribute(p);
		}
	}


	/**
	 * Returns a list of attributes for a product, excluding attributes that
	 * fall under the Product Details tree of attributes.
	 * @param productId
	 * @return
	 */
	protected List<Object> getProductAttributes(String productId, String attributeType) {
		List<Object> params = new ArrayList<>();
		params.add(Status.A.name());
		params.add(productId);
		params.add(DETAILS_ID);

		StringBuilder sql = new StringBuilder(1500);
		sql.append(DBUtil.SELECT_CLAUSE).append("xr.*, a.*, ");
		sql.append("case when arch.product_attribute_group_id is not null then 1 else 0 end as has_archives ");
		sql.append(DBUtil.FROM_CLAUSE);
		sql.append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR xr ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE a ");
		sql.append("ON a.ATTRIBUTE_ID = xr.ATTRIBUTE_ID ");
		sql.append(LEFT_OUTER_JOIN).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR arch ");
		sql.append("on xr.product_attribute_group_id = arch.product_attribute_group_id ");
		sql.append("and arch.product_attribute_id != arch.product_attribute_group_id ");
		sql.append("and arch.status_no = ? ").append(DBUtil.WHERE_CLAUSE);
		sql.append("xr.PRODUCT_ID = ? ");
		sql.append("AND xr.ATTRIBUTE_ID not in ( ");
		sql.append("SELECT child.ATTRIBUTE_ID from ").append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE child ");
		sql.append("INNER JOIN ").append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE parent ");
		sql.append("on parent.ATTRIBUTE_ID = child.PARENT_ID ");
		sql.append("where parent.PARENT_ID = ? ) ");
		if (!StringUtil.isEmpty(attributeType)) {
			sql.append("and TYPE_CD = ? ");
			params.add(attributeType);
		}
		sql.append("and xr.product_attribute_id = xr.product_attribute_group_id ");
		sql.append("ORDER BY xr.ORDER_NO, XR.TITLE_TXT ");

		log.debug(sql+"|"+productId);
		DBProcessor db = new DBProcessor(dbConn);

		// DBProcessor returns a list of objects that need to be individually cast to attributes
		return db.executeSelect(sql.toString(), params, new ProductAttributeVO());
	}


	/**
	 * Update a product or related attribute of a product
	 * @param req
	 * @throws ActionException
	 */
	protected void updateElement(ActionRequest req) throws ActionException {
		ActionTarget action = ActionTarget.valueOf(req.getParameter(ACTION_TARGET));
		DBProcessor db = new DBProcessor(dbConn, (String) customDbSchema);
		switch(action) {
			case PRODUCT:
				saveFullProduct(req, db);
				break;
			case PRODUCTATTRIBUTE:
				ProductAttributeVO attr = new ProductAttributeVO(req);
				saveAttribute(attr, db);
				break;
			case ATTRIBUTE:
				try {
					ProductAttributeTypeVO t = new ProductAttributeTypeVO(req);
					if (checkDups(t)) {
						//Ensure Order No is set properly for Details.
						DetailsField f = EnumUtil.safeValueOf(DetailsField.class, t.getParentId());
						if(f != null) {
							t.setOrderNo(f.getPublicOrder());
						}
						db.save(t);
					}
					if (StringUtil.isEmpty(t.getTypeCd()) && req.hasParameter("modulesetId"))
						populateModuleSets(t, req);
					putModuleData(t);
				} catch (Exception e) {
					throw new ActionException(e);
				}
				break;
			case ALLIANCE:
				ProductAllianceVO a = new ProductAllianceVO(req);
				saveAlliance(a, db);
				break;
			case DETAILSATTRIBUTE:
				saveDetailsAttribute(req);
				break;
			case REGULATION:
				RegulationVO reg = new RegulationVO(req);
				saveRegulation(reg, db);
				break;
			case PRODUCTATTRIBUTEARCHIVEUPDATE:
				attr = new ProductAttributeVO(req);
				updateArchiveNote(attr);
				break;
			default:break;
		}
	}

	/**
	 * Update an Archives Revision Text.
	 * @param attr
	 * @param db
	 */
	private void updateArchiveNote(ProductAttributeVO attr) {
		StringBuilder sql = new StringBuilder(150);
		sql.append("update ").append(getCustomSchema()).append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR x ");
		sql.append("set REVISION_NOTE = ?, update_dt = ? where product_attribute_id = ?");

		try(PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, attr.getRevisionNote());
			ps.setTimestamp(2, Convert.getCurrentTimestamp());
			ps.setString(3, attr.getProductAttributeId());
			ps.executeUpdate();
		} catch (SQLException e) {
			log.error("Error Updating Archive Revision Text", e);
		}
	}

	/**
	 * Ensure that the item we are adding is not already in the system
	 * @param t
	 * @return
	 * @throws SQLException
	 */
	private boolean checkDups(ProductAttributeTypeVO t) throws SQLException {
		StringBuilder sql = new StringBuilder(125);
		sql.append("select attribute_id from ").append(attributes.get(Constants.CUSTOM_DB_SCHEMA));
		sql.append("biomedgps_product_attribute where lower(attribute_nm) = ? and parent_id = ? ");
		
		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, StringUtil.checkVal(t.getAttributeName()).trim().toLowerCase());
			ps.setString(2, t.getParentId());
			
			ResultSet rs = ps.executeQuery();
			
			if (rs.next()) {
				t.setAttributeId(rs.getString("attribute_id"));
				return false;
			}
		}
		
		return true;
	}

	/**
	 * Save all moduleset associations this detail should have. 
	 */
	private void populateModuleSets(ProductAttributeTypeVO t, ActionRequest req) throws ActionException {
		StringBuilder sql = new StringBuilder(250);
		sql.append("insert into ").append(attributes.get(Constants.CUSTOM_DB_SCHEMA)).append("biomedgps_product_moduleset_xr ");
		sql.append("(product_moduleset_id, moduleset_id, attribute_id, create_dt)");
		sql.append("values(?,?,?, CURRENT_TIMESTAMP)");
		
		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			for (String modulesetId : req.getParameterValues("modulesetId")) {
				ps.setString(1, new UUIDGenerator().getUUID());
				ps.setString(2, modulesetId);
				ps.setString(3, t.getAttributeId());
				t.addSectionIds(modulesetId);
				ps.addBatch();
			}
			ps.executeBatch();
		} catch (SQLException e) {
			throw new ActionException(e);
		}
	}

	/**
	 * So all saves needed to update or insert a products core information.
	 * @param req
	 * @param db
	 * @throws ActionException 
	 */
	protected void saveFullProduct(ActionRequest req, DBProcessor db) throws ActionException {
		ProductVO p = new ProductVO(req);
		boolean isInsert = StringUtil.isEmpty(p.getProductId());
		saveProduct(p, db, isInsert);
		saveSections(req, p);
		if (isInsert) {
			generateContent(req, p.getProductId());
			req.setParameter("productId", p.getProductId());
		}
	}


	/**
	 * Generate empty content with titles based of the ContentType enum that
	 * have been selected by the user on product creation.
	 * @param req
	 * @param productId
	 * @throws ActionException
	 */
	private void generateContent(ActionRequest req, String productId) throws ActionException {
		String[] contentList = req.getParameterValues("contentName");
		// If nothing is supplied we can return without issue.
		if (contentList.length == 0) return;

		StringBuilder sql = new StringBuilder(275);
		sql.append(INSERT_INTO).append(customDbSchema);
		sql.append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR(PRODUCT_ATTRIBUTE_ID, PRODUCT_ATTRIBUTE_GROUP_ID, ");
		sql.append("ATTRIBUTE_ID, PRODUCT_ID, TITLE_TXT, ORDER_NO, STATUS_NO, CREATE_DT) ");
		sql.append("VALUES(?,?,?,?,?,?,?,?)");
		log.debug(sql);
		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			for (String contentName : contentList) {
				ContentType type = ContentType.getFromString(contentName);
				if (type == null) continue;
				log.debug(type.getContentName());
				String attrId = new UUIDGenerator().getUUID();
				ps.setString(1, attrId);
				ps.setString(2, attrId);
				ps.setString(3, CONTENT_ATTRIBUTE_ID);
				ps.setString(4, productId);
				ps.setString(5, type.getContentName());
				ps.setInt(6, type.getOrder());
				ps.setString(7, Status.P.toString());
				ps.setTimestamp(8, Convert.getCurrentTimestamp());
				ps.addBatch();
			}

			ps.executeBatch();
		} catch (SQLException e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Save the supplied regulation
	 * @param reg
	 * @param db
	 * @throws ActionException
	 */
	protected void saveRegulation(RegulationVO reg, DBProcessor db) throws ActionException {
		try {
			if (StringUtil.isEmpty(reg.getRegulatorId())) {
				reg.setRegulatorId(new UUIDGenerator().getUUID());
				db.insert(reg);
			} else {
				db.update(reg);
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Delete the currently saved detail attributes and save the supplied list
	 * of attributes
	 * @param req
	 * @throws ActionException
	 */
	protected void saveDetailsAttribute(ActionRequest req) throws ActionException {
		deleteCurrentDetails(req);

		StringBuilder sql = new StringBuilder(225);
		sql.append(INSERT_INTO).append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR ");
		sql.append("(PRODUCT_ATTRIBUTE_ID, PRODUCT_ATTRIBUTE_GROUP_ID, ATTRIBUTE_ID, PRODUCT_ID, CREATE_DT) ");
		sql.append("VALUES(?,?,?,?,?)");

		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			String productId = req.getParameter("productId");
			for (String s : req.getParameterValues("attributeId")) {
				String attrGroupId = new UUIDGenerator().getUUID();
				ps.setString(1, attrGroupId);
				ps.setString(2, attrGroupId);
				ps.setString(3, s);
				ps.setString(4, productId);
				ps.setTimestamp(5, Convert.getCurrentTimestamp());

				ps.addBatch();
			}
			ps.executeBatch();
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Delete all attribute xrs associated with the current product that are
	 * grandchildren of the supplied root attribute id.
	 * @param req
	 * @throws ActionException
	 */
	protected void deleteCurrentDetails(ActionRequest req) throws ActionException {
		StringBuilder sql = new StringBuilder(475);
		sql.append("DELETE FROM ").append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR ");
		sql.append("WHERE ATTRIBUTE_ID in ( ");
		sql.append("SELECT child.ATTRIBUTE_ID from ").append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE child ");
		sql.append("INNER JOIN ").append(customDbSchema).append("BIOMEDGPS_PRODUCT_ATTRIBUTE parent ");
		sql.append("on parent.ATTRIBUTE_ID = child.PARENT_ID ");
		sql.append("where parent.PARENT_ID = ? ) ");
		sql.append("and PRODUCT_ID = ? ");

		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, DETAILS_ID);
			ps.setString(2, req.getParameter("productId"));

			ps.executeUpdate();
		} catch (Exception e) {
			throw new ActionException(e);
		}

	}


	/**
	 * Check whether the supplied alliance needs to be updated or inserted and do so.
	 * @param a
	 * @param db
	 * @throws ActionException
	 */
	protected void saveAlliance(ProductAllianceVO a, DBProcessor db) throws ActionException {
		try {
			if (StringUtil.isEmpty(a.getAllianceId())) {
				a.setAllianceId(new UUIDGenerator().getUUID());
				db.insert(a);
			} else {
				db.update(a);
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}

	}


	/**
	 * Add the supplied sections to the product xr table
	 * @param req
	 * @throws ActionException
	 */
	protected void saveSections(ActionRequest req, ProductVO p) throws ActionException {
		// Delete all sections currently assigned to this product before adding
		// what is on the request object.
		deleteSection(true, p.getProductId());

		// If there is nothing to add return here
		if (!req.hasParameter("sectionId")) return;

		StringBuilder sql = new StringBuilder(225);
		sql.append(INSERT_INTO).append(customDbSchema);
		sql.append("BIOMEDGPS_PRODUCT_SECTION (PRODUCT_SECTION_XR_ID, SECTION_ID, ");
		sql.append("PRODUCT_ID, CREATE_DT) ");
		sql.append("VALUES(?,?,?,?) ");

		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			for (String sectionId : req.getParameterValues("sectionId")) {
				ps.setString(1, new UUIDGenerator().getUUID());
				ps.setString(2, sectionId);
				ps.setString(3, p.getProductId());
				ps.setTimestamp(4, Convert.getCurrentTimestamp());
				ps.addBatch();
			}
			ps.executeBatch();
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Check whether the supplied attribute needs to be inserted or updated and do so.
	 * @param attr
	 * @param db
	 * @throws ActionException
	 */
	protected void saveAttribute(ProductAttributeVO attr, DBProcessor db) throws ActionException {
		attr.calulateOrderNo();
		try {
			if (StringUtil.isEmpty(attr.getProductAttributeId())) {
				attr.setProductAttributeId(new UUIDGenerator().getUUID());
				attr.setProductAttributeGroupId(attr.getProductAttributeId());
				db.insert(attr);
			} else {
				//Clone Existing Attribute Values
				archiveAttribute(attr.getProductAttributeId(), db);

				//Update with New Values
				db.update(attr);
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}

	/**
	* Update the AttributeId of a company attribute and set the archive flag
	* to 1 before inserting.
	* @param companyAttributeId
	* @param db
	*/
	private void archiveAttribute(String companyAttributeId, DBProcessor db) {
		try {

			//Retrieve the existing ProductAttribute from the DB.
			ProductAttributeVO attr = new ProductAttributeVO();
			attr.setProductAttributeId(companyAttributeId);
			db.getByPrimaryKey(attr);

			//Overwrite existing Id with new id.
			attr.setProductAttributeId(new UUIDGenerator().getUUID());

			//Ensure ArchiveFlg is set to 1.
			attr.setStatusNo(Status.A.name());

			//Clear out the createDt so it's autoGenerated.
			attr.setCreateDate(null);

			//Call insert to generate a copy record.
			db.insert(attr);
		} catch (InvalidDataException | DatabaseException e) {
			log.error("Error Processing Code", e);
		}
	}

	/**
	 * Check whether we need to insert or update the supplied vo and do so.
	 * Then update the investors for the product.
	 * @param c
	 * @param db
	 * @throws ActionException
	 */
	protected boolean saveProduct(ProductVO c, DBProcessor db, boolean isInsert) throws ActionException {
		try {
			if (isInsert) {
				c.setProductId(new UUIDGenerator().getUUID());
				db.insert(c);
				return true;
			} else {
				db.update(c);
				return false;
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Check whether the supplied attribute type needs to be inserted or updated and do so.
	 * @param attr
	 * @param db
	 * @param boolean1 
	 * @throws ActionException
	 */
	protected void saveAttributeType(ProductAttributeTypeVO t, DBProcessor db, Boolean insert) throws ActionException {
		try {
			if (insert) {
				db.insert(t);
			} else {
				db.update(t);
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Delete a supplied element
	 * @param req
	 * @throws ActionException
	 */
	protected void deleteElement(ActionRequest req) throws ActionException {
		ActionTarget action = ActionTarget.valueOf(req.getParameter(ACTION_TARGET));
		DBProcessor db = new DBProcessor(dbConn, (String) customDbSchema);
		try {
			switch(action) {
				case PRODUCTATTRIBUTEARCHIVE:
					ProductAttributeVO arch = new ProductAttributeVO(req);
					db.delete(arch);
					break;
				case PRODUCT:
					ProductVO c = new ProductVO(req);
					db.delete(c);
					break;
				case PRODUCTATTRIBUTE:
					ProductAttributeVO attr = new ProductAttributeVO(req);
					db.delete(attr);
					flushArchives(attr.getProductAttributeId());
					break;
				case ATTRIBUTE:
					ProductAttributeTypeVO t = new ProductAttributeTypeVO(req);
					db.delete(t);
					break;
				case ALLIANCE:
					ProductAllianceVO a = new ProductAllianceVO(req);
					db.delete(a);
					break;
				case REGULATION:
					RegulationVO reg = new RegulationVO(req);
					db.delete(reg);
					break;
				default:break;
			}
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}

	/**
	* Flush out Archived Attribute Records related to given productAttributeId.
	* @param productAttributeId - I'd we're flushing.
	* @throws SQLException
	*/
	private void flushArchives(String productAttributeId) throws SQLException {
		StringBuilder sql = new StringBuilder(150);
		sql.append(DBUtil.DELETE_CLAUSE).append(DBUtil.FROM_CLAUSE);
		sql.append(getCustomSchema()).append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR ");
		sql.append(DBUtil.WHERE_CLAUSE).append("product_attribute_group_id = ?");
		try(PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, productAttributeId);
			ps.executeUpdate();
		}
	}

	/**
	 * Delete section xrs for a product. Deletes come in single xr deletion and
	 * full wipes used when new xrs are being saved.
	 * @param full
	 * @param id
	 * @throws ActionException
	 */
	protected void deleteSection(boolean full, String id) throws ActionException {
		StringBuilder sql = new StringBuilder(150);
		sql.append("DELETE FROM ").append(customDbSchema);
		sql.append("BIOMEDGPS_PRODUCT_SECTION WHERE ");
		if (full) {
			sql.append("PRODUCT_ID = ? ");
		} else {
			sql.append("PRODUCT_SECTION_XR_ID = ? ");
		}
		log.debug(sql+"|"+id);
		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, id);

			ps.executeUpdate();
		} catch (Exception e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Take in front end requests and direct them to the proper delete or update method
	 */
	@Override
	public void build(ActionRequest req) throws ActionException {
		String buildAction = req.getParameter("buildAction");
		String msg = StringUtil.capitalizePhrase(buildAction) + " completed successfully.";
		try {
			if ("update".equals(buildAction)) {			
				updateElement(req);
			} else if("delete".equals(buildAction)) {
				deleteElement(req);
			} else if ("orderUpdate".equals(buildAction)) {
				updateOrder(req);
				// We don't want to send redirects after an order update
				return;
			} else if("bulkLinkUpdate".equals(buildAction)) {
				new ManagementActionUtil(dbConn, attributes).bulkUpdateAttributeLinks(req);
			}
		} catch (Exception e) {
			log.error("Error attempting to build: ", e);
			msg = StringUtil.capitalizePhrase(buildAction) + " failed to complete successfully. Please contact an administrator for assistance";
		}
		String productId = req.hasParameter("pkId")? req.getParameter("pkId") : req.getParameter("productId");
		
		if (!StringUtil.isEmpty(productId)) {
			String status = req.getParameter("statusNo");
			if (StringUtil.isEmpty(status))
				status = findStatus(productId);
			updateSolr(productId, status);
		}
		
		if (!Convert.formatBoolean(req.getParameter("json")))
			redirectRequest(msg, buildAction, req);
	}

	/**
	 * Determine what is being reordered and call the proper method.
	 * @param req
	 * @throws ActionException
	 */
	protected void updateOrder(ActionRequest req) throws ActionException {
		ActionTarget action = ActionTarget.valueOf(req.getParameter(ACTION_TARGET));

		switch (action) {
			case ALLIANCE:
				updateAllianceOrder(req);
				break;
			case PRODUCTATTACH:
			case PRODUCTLINK:
			case PRODUCTATTRIBUTE:
				updateAttributeOrder(req);
				break;
			default:
				break;
		}
	}


	/**
	 * Alter the order of the supplied alliances
	 * @param req
	 * @throws ActionException
	 */
	private void updateAllianceOrder(ActionRequest req) throws ActionException {
		StringBuilder sql = new StringBuilder(150);
		sql.append("UPDATE ").append(customDbSchema);
		sql.append("BIOMEDGPS_PRODUCT_ALLIANCE_XR SET ORDER_NO = ? WHERE PRODUCT_ALLIANCE_XR_ID = ? ");

		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			populateReorderBatch(ps, req, "allianceId");

			ps.executeBatch();
		} catch (SQLException e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Alter the order of the supplied attributes
	 * @param req
	 * @throws ActionException
	 */
	protected void updateAttributeOrder(ActionRequest req) throws ActionException {
		StringBuilder sql = new StringBuilder(150);
		sql.append("UPDATE ").append(customDbSchema);
		sql.append("BIOMEDGPS_PRODUCT_ATTRIBUTE_XR SET ORDER_NO = ? WHERE PRODUCT_ATTRIBUTE_ID = ? ");

		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			populateReorderBatch(ps, req, "productAttributeId");

			ps.executeBatch();
		} catch (SQLException e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Loop over the orders and id field supplied in the action request
	 * and add them to the batch statement
	 * @param ps
	 * @param req
	 * @param idField
	 * @throws SQLException
	 */
	protected void populateReorderBatch(PreparedStatement ps, ActionRequest req, String idField) throws SQLException {
		String[] ids = req.getParameterValues(idField);
		for (int i=0; i < ids.length; i++) {
			ps.setInt(1, i+1);
			ps.setString(2, ids[i]);
			ps.addBatch();
		}
	}


	/**
	 * Get the status of the supplied company.
	 * @param marketId
	 * @return
	 * @throws ActionException
	 */
	protected String findStatus(String productId) throws ActionException {
		StringBuilder sql = new StringBuilder(125);
		sql.append("SELECT STATUS_NO from ").append(customDbSchema);
		sql.append("BIOMEDGPS_PRODUCT WHERE PRODUCT_ID = ? ");

		try (PreparedStatement ps = dbConn.prepareStatement(sql.toString())) {
			ps.setString(1, productId);
			ResultSet rs = ps.executeQuery();
			if (rs.next())
				return rs.getString("STATUS_NO");

		} catch (SQLException e) {
			throw new ActionException(e);
		}

		// If we didn't find a market with this id the action was a delete and solr needs to recognize that
		return "D";
	}



	/**
	 * Push the updates to solr
	 * @param req
	 * @param buildAction
	 * @throws ActionException
	 */
	protected void updateSolr(String productId, String status) throws ActionException {
		Properties props = new Properties();
		props.putAll(getAttributes());
		BiomedProductIndexer indexer = new BiomedProductIndexer(props);
		indexer.setDBConnection(dbConn);
		
		try {
			if ("D".equals(status) || "A".equals(status)) {
				if (productId.length() < AdminControllerAction.DOC_ID_MIN_LEN)
					productId = Section.PRODUCT.name() + "_" +productId;
				indexer.purgeSingleItem(productId, false);
			} else {
				indexer.indexItems(productId);
			}
		} catch (IOException e) {
			throw new ActionException(e);
		}
	}


	/**
	 * Build the redirect for build requests
	 * @param msg
	 * @param buildAction
	 * @param req
	 */
	protected void redirectRequest(String msg, String buildAction, ActionRequest req) {
		PageVO page = (PageVO) req.getAttribute(Constants.PAGE_DATA);
		// Redirect the user to the appropriate page
		StringBuilder url = new StringBuilder(128);
		url.append(page.getFullPath()).append("?actionType=productAdmin&").append("msg=").append(msg);

		// Only add a tab parameter if one was provided.
		if (req.hasParameter("tab")) {
			url.append("&tab=").append(req.getParameter("tab"));
		}
		//if a product is being deleted do not redirect the user to a product page
		if (!"delete".equals(buildAction) || 
				ActionTarget.valueOf(req.getParameter(ACTION_TARGET)) != ActionTarget.PRODUCT) {
			url.append("&productId=").append(req.getParameter("productId"));
		}

		if ("ATTRIBUTE".equals(req.getParameter(ACTION_TARGET)))
			url.append("&").append(ACTION_TARGET).append("=ATTRIBUTE");

		req.setAttribute(Constants.REDIRECT_REQUEST, Boolean.TRUE);
		req.setAttribute(Constants.REDIRECT_URL, url.toString());
	}

}
