package com.ram.action.products;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.ram.datafeed.data.KitLayerVO;
import com.siliconmtn.action.ActionException;
import com.siliconmtn.action.ActionInitVO;
import com.siliconmtn.action.SMTActionInterface;
import com.siliconmtn.db.DBUtil;
import com.siliconmtn.http.SMTServletRequest;
import com.siliconmtn.util.Convert;
import com.smt.sitebuilder.action.SBActionAdapter;
import com.smt.sitebuilder.common.ModuleVO;
import com.smt.sitebuilder.common.constants.Constants;

/****************************************************************************
 * <b>Title</b>: KitLayerAction.java
 * <p/>
 * <b>Project</b>: WC_Custom
 * <p/>
 * <b>Description: </b> Action that handles all calls to creating and editing
 * Kit Layers for a product. We also handle calling out to the coordinate
 * parser to extract coordinate data from the Canvas Elements JSON Data that
 * is returned on update.
 * <p/>
 * <b>Copyright:</b> Copyright (c) 2014
 * <p/>
 * <b>Company:</b> Silicon Mountain Technologies
 * <p/>
 * 
 * @author raptor
 * @version 1.0
 * @since May 20, 2014
 *        <p/>
 *        <b>Changes: </b>
 *************************************************************************** 
 */
public class KitLayerAction extends SBActionAdapter {

	public static final String KIT_LAYER_ID = "kitLayerId";
	
	/**
	 * Default Constructor
	 */
	public KitLayerAction() {
		super();
	}

	/**
	 * General Constructor with ActionInitVO Data
	 * @param actionInit
	 */
	public KitLayerAction(ActionInitVO actionInit) {
		super(actionInit);
		
	}
	
	/**
	 * We handle inserting or updating information about kit layers here. 
	 * We also handle calling out to extract Coordinate Data from the canvas
	 * elements JSON Data that gets returned at the end if there is any present.
	 * Lastly, if this is an insert, we get the inserted primary key off the 
	 * preparedStatement and return that to the view.
	 */
	@Override
	public void build(SMTServletRequest req) throws ActionException {
		
		//Deactivate request validation so we can save the Json Data for canvas element.
		req.setValidateInput(false);
		
		//Build initial success map.
		Map<String, String> result = new HashMap<String, String>();
		result.put("success", "true");
		result.put("msg", "Data Successfully Updated");
		
		//Build Query depending on if this is insert or update.
		StringBuilder sb = new StringBuilder();
		if(req.hasParameter(KIT_LAYER_ID)) {
			sb.append("update ").append(attributes.get(Constants.CUSTOM_DB_SCHEMA));
			sb.append("RAM_KIT_LAYER set IMAGE_PATH_URL = ?, LAYOUT_DEPTH_NO = ?, ");
			sb.append("UPDATE_DT = ?, ACTIVE_FLG = ?, JSON_DATA = ? ");
			sb.append("where KIT_LAYER_ID = ?");
		}
		else {
			sb.append("insert into ").append(attributes.get(Constants.CUSTOM_DB_SCHEMA));
			sb.append("RAM_KIT_LAYER (IMAGE_PATH_URL, LAYOUT_DEPTH_NO, CREATE_DT, ");
			sb.append("ACTIVE_FLG, PRODUCT_ID) values (?,?,?,?,?)");
		}

		//Log sql Statement for verification
		log.debug("sql: " + sb.toString());
		
		PreparedStatement ps = null;
		
		try {
			ps = dbConn.prepareStatement(sb.toString());
			ps.setString(1, req.getParameter("imagePathUrl"));
			ps.setString(2, req.getParameter("layoutDepthNo"));
			ps.setTimestamp(3, Convert.getCurrentTimestamp());
			ps.setInt(4, Convert.formatInteger(Convert.formatBoolean(req.getParameter("activeFlag"))));
			
			//Set additional parameters based on isnert or update.
			if(req.hasParameter(KIT_LAYER_ID)) {
				ps.setString(5, req.getParameter("jsonData"));
				ps.setInt(6, Convert.formatInteger(req.getParameter(KIT_LAYER_ID)));
			} else {
				ps.setInt(5, Convert.formatInteger(req.getParameter("kitId")));
			}
			
			ps.execute();
		} catch(SQLException sqle) {
			log.error(sqle);
			result.put("success", "false");
			result.put("msg", "Problem Saving Record");
		} finally {
			try {
				/*
				 * Since the primary key is autogenerated, we need to get that back
				 * from the PreparedStatement so that the view can work with valid
				 * information.
				 */
				ResultSet rs = ps.getGeneratedKeys();
				if(rs.next())
					result.put("kitLayerId", rs.getString(1));
				DBUtil.close(ps);
			} catch(Exception e) {}
		}
		
		/*
		 * If this is an update, we need to parse the Canvas Json element to
		 * get the Coordinate data for the kit layer products.
		 */
		if(req.hasParameter(KIT_LAYER_ID)) {
			SMTActionInterface sai = new KitCoordinateParser(this.actionInit);
			sai.setAttributes(attributes);
			sai.setDBConnection(dbConn);
			sai.build(req);
		}
		super.putModuleData(result);

	}

	/**
	 * We can't delete anything in RAM due to sync issues so we mark items
	 * inactive.  This handles marking a given kitLayer as inactive.
	 */
	@Override
	public void delete(SMTServletRequest req) throws ActionException {
		//Build Query
		StringBuilder sb = new StringBuilder();
		sb.append("update ").append(attributes.get(Constants.CUSTOM_DB_SCHEMA));
		sb.append("RAM_KIT_LAYER set ACTIVE_FLG = 0 ");
		sb.append("where KIT_LAYER_ID = ? order by LAYER_DEPTH_NO");

		//Log sql Statement for verification
		log.debug("sql: " + sb.toString());
		
		PreparedStatement ps = null;
		
		try {
			ps = dbConn.prepareStatement(sb.toString());
			ps.setString(1, req.getParameter(KIT_LAYER_ID));
			ps.execute();
			((ModuleVO)attributes.get(Constants.MODULE_DATA)).setErrorMessage("Deactivation Successful");
		} catch(SQLException sqle) {
			log.error(sqle);
			((ModuleVO)attributes.get(Constants.MODULE_DATA)).setErrorMessage("Deactivation Failed");
			throw new ActionException(sqle);
		} finally {
			DBUtil.close(ps);
		}		
		
	}

	/**
	 * Retrieve all the kit layers for a given productId
	 */
	@Override
	public void retrieve(SMTServletRequest req) throws ActionException {
		
		List<KitLayerVO> layers = new ArrayList<KitLayerVO>();
		KitLayerVO layer = new KitLayerVO();
				
		//Build Query
		StringBuilder sb = new StringBuilder();
		sb.append("select * from ").append(attributes.get(Constants.CUSTOM_DB_SCHEMA));
		sb.append("RAM_KIT_LAYER where PRODUCT_ID = ?");
		
		sb.append(" order by LAYOUT_DEPTH_NO, KIT_LAYER_ID");
		
		//Log sql Statement for verification
		log.debug("sql: " + sb.toString());
		
		PreparedStatement ps = null;
		
		try {
			ps = dbConn.prepareStatement(sb.toString());
			ps.setString(1, req.getParameter("productId"));
			
			ResultSet rs = ps.executeQuery();
			
			//Build list of layers and set the JSON_DATA on them.
			while(rs.next()) {
				layer = new KitLayerVO(rs, false);
				layer.setJsonData(rs.getString("JSON_DATA"));
				layers.add(layer);
			}
		} catch(SQLException sqle) {
			log.error(sqle);
			throw new ActionException(sqle);
		} finally {
			DBUtil.close(ps);
		}
		
		//Set the layers on the Module Data.
		this.putModuleData(layers, layers.size(), false);
	}

	/* (non-Javadoc)
	 * @see com.smt.sitebuilder.action.SBActionAdapter#update(com.siliconmtn.http.SMTServletRequest)
	 */
	@Override
	public void update(SMTServletRequest req) throws ActionException {
		
	}
	
}
