SELECT a.objectId
      ,[title]
      ,[lname]
      ,[fname]
      ,[clinic]
      ,[address1]
      ,[address2]
      ,[address3]
      ,[city]
      ,b.state
      ,[zipcode]
      ,[daytimephone]
      ,[fax]
      ,[email]
      ,[tier]
      ,[personTypeId]
      ,[website]
      ,[cv]
      ,[photo]
      ,[languagesspoken]
      ,[appointmentInfo]
      ,a.status
      ,a.comments
      ,case ProspectStatus 
			when 0 then 'Customer'
			when 1 then 'Prospect'
			when 2 then 'Fellow'
			when 3 then 'PCP'
		end	as ProspectType
      ,[CellPhone]
      ,[MI]
      ,[suffix]
      ,[speciality]
      ,[other_type]
      ,[Prospect]
      ,[department]
      ,[office_manager]
      ,[OM_phone]
      ,[RN]
      ,[PA]
      ,[other_staff]
      ,[UPIN]
      ,[sec_address1]
      ,[sec_address2]
      ,[sec_city]
      ,c.state
      ,[sec_zip]
      ,[sec_phone]
      ,[sec_fax]
      ,[sec_email]
      ,[sec_website]
      ,[home_address1]
      ,[home_address2]
      ,[home_city]
      ,f.state
      ,[home_zip]
      ,[home_fax]
      ,[home_email]
      ,[notes]
      ,[except1]
      ,[except2]
      ,[tempx]
      ,[home_phone]
      ,[other_phone]
      ,[pager]
      ,[spouse]
      ,[children]
      ,[scs_per_year]
      ,[ans_meetings_attended]
      ,[ans_services_used]
      ,[preferred_mailing_address]
      ,[mail_status]
      ,[FAP]
      ,[pt_other]
      ,[practice_website]
      ,[MIDDLEINITIALNAME]
      ,a.state
      ,[sales_region]
      ,[PHYSICIANTYPE]
      ,[PHYSICIAN_ID]
      ,[office_manager_phone]
      ,[office_manager_email]
      ,[RN_phone]
      ,[RN_email]
      ,[PA_phone]
      ,[PA_email]
      ,[other_staff_phone]
      ,[other_staff_email]
      ,[SC]
      ,[SC_Phone]
      ,[SC_Email]
      ,[third_address1]
      ,[third_address2]
      ,[third_city]
      ,d.state
      ,[third_zip]
      ,[third_phone]
      ,[third_fax]
      ,[third_email]
      ,[third_website]
      ,[fourth_address1]
      ,[fourth_address2]
      ,[fourth_city]
      ,e.state
      ,[fourth_zip]
      ,[fourth_phone]
      ,[fourth_fax]
      ,[fourth_email]
      ,[fourth_website]
      ,[chk_ThirdMail]
      ,[chk_FourthMail]
      ,[sec_Status]
      ,[third_Status]
      ,[fourth_Status]
      ,[home_Status]
  FROM [ANS_EXTRANET].[dbo].[obj_phytemp] a
left outer join obj_state b on a.stateid = b.objectId
left outer join obj_state c on a.sec_state = c.objectId
left outer join obj_state d on a.third_state = d.objectId
left outer join obj_state e on a.fourth_state = e.objectId
left outer join obj_state f on a.home_state = f.objectId